name: Build-CI

on: [pull_request, push]

jobs:

  approve: # First step
    runs-on: ubuntu-latest

    steps:
    - name: Approve
      run: echo For security reasons, all pull requests to this repository need to be approved first before running any automated CI.

  build:
    runs-on: ubuntu-latest

    needs: [approve] # Require the first step to finish
    environment:
      name: IO
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Install library
      run: python3 setup.py install

    - name: Install sphinx
      run: pip3 install pylint Sphinx sphinx-rtd-theme

    - name: Run unittests
      env:
        SECRET_IO_KEY: ${{ secrets.CI_IO_KEY }}
        SECRET_IO_USER: ${{ secrets.CI_IO_USERNAME }}
      run: |
        cd tests/
        ADAFRUIT_IO_KEY=$SECRET_IO_KEY ADAFRUIT_IO_USERNAME=$SECRET_IO_USER python -m unittest discover
        cd ..

    - name: Generate documentation
      run: |
        cd docs && sphinx-build -E -W -b html . _build/html && cd ..
