name: Release CI

on:
  release:
    types: [published]

jobs:
  upload-pypi:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Check For pyproject.toml
      id: need-pypi
      run: |
        echo ::set-output name=pyproject-toml::$( find . -wholename './pyproject.toml' )
    - name: Set up Python
      if: contains(steps.need-pypi.outputs.pyproject-toml, 'pyproject.toml')
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      if: contains(steps.need-pypi.outputs.pyproject-toml, 'pyproject.toml')
      run: |
        python -m pip install --upgrade pip
        pip install build wheel twine
    - name: Build and publish
      if: contains(steps.need-pypi.outputs.pyproject-toml, 'pyproject.toml')
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        for file in $(find -not -path "./.*" -not -path "./docs*" \( -name "*.py" -o -name "*.toml" \) ); do
            sed -i -e "s/0.0.0/${{github.event.release.tag_name}}/" $file;
        done;
        python -m build
        twine upload dist/*